name: Study Build

on: push
# on:
#   push:
#     branches:
#       - study

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - name: Yarn install
        run: yarn install
      - name: Build for chrome
        run: yarn run build chrome
        env:
          BROWSER_USER: ${{ secrets.BROWSER_USER }}
          BROWSER_PASSWORD: ${{ secrets.BROWSER_PASSWORD }}
      - name: Build for firefox
        run: yarn run build firefox
        env:
          BROWSER_USER: ${{ secrets.BROWSER_USER }}
          BROWSER_PASSWORD: ${{ secrets.BROWSER_PASSWORD }}
      - name: Build for opera
        run: yarn run build opera
        env:
          BROWSER_USER: ${{ secrets.BROWSER_USER }}
          BROWSER_PASSWORD: ${{ secrets.BROWSER_PASSWORD }}
      - name: Build for edge
        run: yarn run build edge
        env:
          BROWSER_USER: ${{ secrets.BROWSER_USER }}
          BROWSER_PASSWORD: ${{ secrets.BROWSER_PASSWORD }}
      - name: Release if tagged
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump github ref
        env:
          GITHUB_REF: ${{ github.ref }}
        run: echo "$GITHUB_REF"
      - name: Check github ref
        env:
          GITHUB_REF_STARTS: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "$GITHUB_REF_STARTS"
      - name: ls
        run: ls -lh
      - name: ls
        run: ls -lh packages
